spring.application.name=URLShortner
spring.app_url=http://localhost:8080/
spring.client_url=http://localhost:3000/
jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address = 0.0.0.0
server.port = 8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
