spring.application.name=URLShortner
spring.env=${ENV}
spring.app_url=${SERVER_URL}
spring.client_url=${CLIENT_URL}
jwt.secret=${JWT_SECRET}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#server.address = {0.0.0.0}
#server.port = 8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=asifstar136@gmail.com
# Paste the 16-character App Password here WITHOUT spaces:
spring.mail.password=jbtrjvdpvflyevlu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Keep this as your actual Gmail address.
# Gmail will ignore any fake domain you put here.
app.mail.from-address=asifstar136@gmail.com
